/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 iphone.glb 
*/
import * as THREE from 'three'
import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: { [key: string]: THREE.Mesh }
  materials: { [key: string]: THREE.MeshStandardMaterial }
}

export const Model = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/iphone.glb') as unknown as GLTFResult

  const group = useRef<THREE.Group | null>(null)

  materials.jUggraQHQxDJpnM.roughness = 0
  materials.jUggraQHQxDJpnM.metalness = 1

  useLayoutEffect(() => {
    const y = new THREE.Vector3(0, 1, 0)
    group.current?.rotateOnWorldAxis(y, Math.PI / 1)
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -8.059, 0]}>
        <mesh
          geometry={nodes.GoKkDPUheDuuSeZ.geometry}
          material={materials.FjQZkOEFcAMgVKb}
          position={[0.374, 15.312, -0.386]}
          scale={0.535}
        />
        <mesh
          geometry={nodes.LLCOsMNMwTSiaFM_0.geometry}
          material={materials.jUggraQHQxDJpnM}
          position={[0, 8.059, -0.386]}
          scale={7.746}
        />
        <mesh
          geometry={nodes.mCHktZAFyMAJfef.geometry}
          material={materials.XioMmaZGUXvxXPb}
          position={[0, 8.059, -0.365]}
          scale={7.961}
        />
        <mesh
          geometry={nodes.dhklRpTwbkGOiTk.geometry}
          material={materials.fexrCBexEqONlzJ}
          position={[-0.734, 15.312, -0.35]}
          scale={0.208}
        />
        <mesh
          geometry={nodes.ffAKcDPUgFPpzDm.geometry}
          material={materials.VlnkJNnmZmryUEK}
          position={[-0.734, 15.312, -0.347]}
          scale={0.172}
        />
        <mesh
          geometry={nodes.rhWSVMrzmgmACdq.geometry}
          material={materials.GoEESZWjCZpqeOD}
          position={[-0.734, 15.312, -0.321]}
          scale={0.078}
        />
        <mesh
          geometry={nodes.TpYiAaTOnMgRFmX_0.geometry}
          material={materials.pAavhFVnCAgSnSH}
          position={[-0.734, 15.312, -0.386]}
          scale={0.168}
        />
        <mesh
          geometry={nodes.kkKyyQuSQljBsvq.geometry}
          material={materials.GCTfChbRIgBmWbe}
          position={[-0.734, 15.312, -0.333]}
          scale={0.078}
        />
      </group>
      <group position={[0, -8.06, 0]}>
        <mesh
          geometry={nodes.fmPCLkRSemlQWac.geometry}
          material={materials.PLMruZnLcxoCgNt}
          position={[-0.665, 12.395, 0.492]}
          scale={0.31}
        />
        <mesh
          geometry={nodes.YPoKloEgOhaAHnb.geometry}
          material={materials.loFcbeOTkLALGur}
          position={[0.012, 8.239, 0.394]}
          scale={1.063}
        />
        <mesh
          geometry={nodes.ySMlAnxbqcOOfYN_0.geometry}
          material={materials.bliqaGpTvCuZHuk}
          position={[-1.561, 13.722, 0.335]}
          scale={1.917}
        />
        <mesh
          geometry={nodes.MZgVlnVREwAXmWu_0.geometry}
          material={materials.TrnkWAfGduLgqLM}
          position={[0, 8.06, 0.453]}
          scale={7.964}
        />
        <mesh
          geometry={nodes.LQmVKBDUfvlduwU.geometry}
          material={materials.qzKHApwituZTUxC}
          position={[-1.26, 11.407, 0.487]}
          scale={4.232}
        />
        <mesh
          geometry={nodes.jxlpVheMoDZjVdT.geometry}
          material={materials.XioMmaZGUXvxXPb}
          position={[-1.556, 13.722, 0.718]}
          scale={1.659}
        />
        <mesh
          geometry={nodes.QUgUcmNrbmAQdPa.geometry}
          material={materials.VlnkJNnmZmryUEK}
          position={[-1.556, 13.722, 0.611]}
          scale={1.605}
        />
        <mesh
          geometry={nodes.DWuaFbuiStCtHXh.geometry}
          material={materials.VlnkJNnmZmryUEK}
          position={[-1.549, 13.722, 0.58]}
          scale={1.604}
        />
        <mesh
          geometry={nodes.KEoybOafRtqNJNh.geometry}
          material={materials.IfqLTOjymCZMuVu}
          position={[-1.556, 14.205, 0.448]}
          scale={1.698}
        />
        <mesh
          geometry={nodes.XaStmvbQicYGoTn.geometry}
          material={materials.IfqLTOjymCZMuVu}
          position={[-2.446, 12.757, 0.448]}
          scale={0.812}
        />
        <mesh
          geometry={nodes.SkYYDNrQKqVDRge.geometry}
          material={materials.GCTfChbRIgBmWbe}
          position={[-1.534, 13.697, 0.612]}
          scale={1.163}
        />
        <mesh
          geometry={nodes.jllDjFkFZNzYOGW.geometry}
          material={materials.GoEESZWjCZpqeOD}
          position={[-1.629, 13.714, 0.568]}
          scale={1.175}
        />
        <mesh
          geometry={nodes.nHCDQLdTvgMPJbp.geometry}
          material={materials.pUfGAKnCgtMMbbm}
          position={[-1.551, 13.722, 0.764]}
          scale={1.611}
        />
        <mesh
          geometry={nodes.ZCtyoMmbuhknTJj.geometry}
          material={materials.erHrUfZxAtkfXqO}
          position={[-1.493, 13.66, 0.636]}
          scale={1.48}
        />
        <mesh
          geometry={nodes.EYwxmcMJdavFtfW.geometry}
          material={materials.MeiGPKHwBMVqGNQ}
          position={[-1.556, 13.722, 0.811]}
          scale={1.605}
        />
        <mesh
          geometry={nodes.YriphandxAMCCeO.geometry}
          material={materials.yuFXHUhPQDoVApU}
          position={[-1.556, 13.239, 0.674]}
          scale={1.698}
        />
        <mesh
          geometry={nodes.ixErOejazQORIfP.geometry}
          material={materials.yuFXHUhPQDoVApU}
          position={[-2.446, 14.687, 0.675]}
          scale={0.812}
        />
        <mesh
          geometry={nodes.gfCaTdiXaVSAvAF_0.geometry}
          material={materials.ZyKhfPnbNOCYIny}
          position={[-0.665, 15.084, 0.522]}
          scale={0.299}
        />
        <mesh
          geometry={nodes.NXKAkZjsnbPTLxk_0.geometry}
          material={materials.EcHAJKlkagvhESV}
          position={[-0.665, 15.084, 0.517]}
          scale={0.272}
        />
        <mesh
          geometry={nodes.QouRlcwrCgGeXyH_0.geometry}
          material={materials.hgmDQvqtKSacBdB}
          position={[-0.665, 15.084, 0.568]}
          scale={0.333}
        />
        <mesh
          geometry={nodes.CifRJRFlybUhpcD.geometry}
          material={materials.IfqLTOjymCZMuVu}
          position={[-0.666, 15.084, 0.498]}
          scale={0.334}
        />
        <mesh
          geometry={nodes.WaDbzrqgLcHkRTX.geometry}
          material={materials.EnwhLiFdMDwiUyz}
          position={[-0.666, 15.084, 0.53]}
          scale={0.328}
        />
        <mesh
          geometry={nodes.MZiAbIpINzxMuaJ_0.geometry}
          material={materials.TrnkWAfGduLgqLM}
          position={[-0.088, 12.711, 0.536]}
          scale={0.055}
        />
        <mesh
          geometry={nodes.jpYEgDQfzzGREjL.geometry}
          material={materials.VlnkJNnmZmryUEK}
          position={[-0.088, 12.711, 0.405]}
          scale={0.056}
        />
        <mesh
          geometry={nodes.FCnUJNLAiKvmJAc_0.geometry}
          material={materials.IfqLTOjymCZMuVu}
          position={[-0.088, 12.711, 0.492]}
          scale={0.086}
        />
      </group>
      <group position={[-0.007, -8.06, 0]}>
        <mesh
          geometry={nodes.TvbvbWsxdamuUZs.geometry}
          material={materials.XvdlxyjrKESiFay}
          position={[-0.002, 15.981, -0.332]}
          scale={0.963}
        />
        <mesh
          geometry={nodes.vpUhSFYUYpnDUQE.geometry}
          material={materials.VlnkJNnmZmryUEK}
          position={[0, 15.985, -0.308]}
          scale={0.954}
        />
        <mesh
          geometry={nodes.VglCddniAjuXwWP.geometry}
          material={materials.IIOPDiBWBbrUopx}
          position={[0.001, 0.032, 0.002]}
          scale={0.711}
        />
        <mesh
          geometry={nodes.XdgYNqkrKoAIJsp.geometry}
          material={materials.qTzpZGPXrrlpDsm}
          position={[0, 8.06, 0]}
          scale={8.06}
        />
        <mesh
          geometry={nodes.SLEuRDFLKhfUOyE.geometry}
          material={materials.nLgTjJkjjIwxPzH}
          position={[0, 6.12, 0]}
          scale={6.12}
        />
        <mesh
          geometry={nodes.BILckvpwXOytcMs.geometry}
          material={materials.initialShadingGroup}
          position={[-0.112, 0.124, 0]}
          scale={1.997}
        />
        <mesh
          geometry={nodes.MVWilhydUNwPxpT.geometry}
          material={materials.fhuhwvvbmZNTsNo}
          position={[0.002, 0.49, -0.009]}
          scale={0.439}
        />
        <mesh
          geometry={nodes.tYhdRFkjheTEnwh.geometry}
          material={materials.euLqrXMAOeSzxXG}
          position={[0.002, 0.57, -0.043]}
          scale={0.439}
        />
        <mesh
          geometry={nodes.lWFljklIAvFvrBM_0.geometry}
          material={materials.toZkefdtnUhLKyP}
          position={[0, 0.016, 0.001]}
          scale={0.404}
        />
        <mesh
          geometry={nodes.mZCSizhtifxXBqG_0.geometry}
          material={materials.myxBndjHzHABgaf}
          position={[0, 0.126, 0.001]}
          scale={0.372}
        />
        <mesh
          geometry={nodes.pkonsGObqbDcbjn_0.geometry}
          material={materials.qTzpZGPXrrlpDsm}
          position={[0, 0, 0.001]}
          scale={0.437}
        />
        <mesh
          geometry={nodes.WUgXyTEbZmkapMh_0.geometry}
          material={materials.nfKhILGSzwibuSI}
          position={[0, 0.288, 0.001]}
          scale={0.37}
        />
        <mesh
          geometry={nodes.quvFSzOoArSvcXY.geometry}
          material={materials.HTVLbrDhlLdibKi}
          position={[-0.218, 0.084, 0]}
          scale={2.115}
        />
        <mesh
          geometry={nodes.jiUeIJQcPqDOUIZ.geometry}
          material={materials.VlnkJNnmZmryUEK}
          position={[0.028, 6.146, 0]}
          scale={6.094}
        />
        <mesh
          geometry={nodes.rxiMoNrvziDIZct.geometry}
          material={materials.WeYJTXtSqeWejVb}
          position={[0, 10.935, 0]}
          scale={3.916}
        />
        <mesh
          geometry={nodes.LcaTrKQHGWZApgK.geometry}
          material={materials.WSDoIreTMPBuTxz}
          position={[3.866, 12.992, 0.001]}
          scale={0.309}
        />
        <mesh
          geometry={nodes.YyStFrQFolEKwWF.geometry}
          material={materials.yuFXHUhPQDoVApU}
          position={[3.842, 7.47, 0]}
          scale={0.809}
        />
        <mesh
          geometry={nodes.dsCQvEsFBIAHfbb.geometry}
          material={materials.VlnkJNnmZmryUEK}
          position={[3.83, 6.799, 0.001]}
          scale={0.065}
        />
        <mesh
          geometry={nodes.hImVmspNdsOatRs.geometry}
          material={materials.WSDoIreTMPBuTxz}
          position={[3.846, 6.8, 0]}
          scale={0.07}
        />
        <mesh
          geometry={nodes.SpKnavUGNMxGglY.geometry}
          material={materials.WeYJTXtSqeWejVb}
          position={[3.847, 7.47, 0]}
          scale={0.799}
        />
        <mesh
          geometry={nodes.OcdXOLSkbIPgJqo_0.geometry}
          material={materials.uApvtlLvHnjNKSG}
          position={[0, 8.06, 0]}
          scale={8.06}
        />
      </group>
      <mesh
        geometry={nodes.SSwNHydlPxsUYYx.geometry}
        material={materials.VlnkJNnmZmryUEK}
        position={[-0.017, 0, 0]}
        scale={8.015}
      />
    </group>
  )
}

export default Model

useGLTF.preload('/iphone.glb')
